USE Fatec
GO

CREATE TABLE Cliente
(
 Id				INT IDENTITY	NOT NULL,
 Nome			VARCHAR(100)	NOT NULL,
 DataNascimento DATETIME		NOT NULL,
 Endereco		VARCHAR(100)	NOT NULL,
 Cidade			VARCHAR(100)	NOT NULL
)